version: '3'

services:
  db:
    image: mongo
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASS}'
      MONGO_INITDB_DATABASE: '${DB_NAME}'
    volumes:
      - /mongo:/data/db
