export const FOOD_LIST_REQUEST = 'FOOD_LIST_REQUEST';
export const FOOD_LIST_SUCCESS = 'FOOD_LIST_SUCCESS';
export const FOOD_LIST_FAIL = 'FOOD_LIST_FAIL';
export const FOOD_LIST_CLEAR = 'FOOD_LIST_CLEAR';

export const FOOD_ADD_REQUEST = 'FOOD_ADD_REQUEST';
export const FOOD_ADD_SUCCESS = 'FOOD_ADD_SUCCESS';
export const FOOD_ADD_FAIL = 'FOOD_ADD_FAIL';
export const FOOD_ADD_CLEAR = 'FOOD_ADD_CLEAR';

export const FOOD_DETAILS_REQUEST = 'FOOD_DETAILS_REQUEST';
export const FOOD_DETAILS_SUCCESS = 'FOOD_DETAILS_SUCCESS';
export const FOOD_DETAILS_FAIL = 'FOOD_DETAILS_FAIL';
export const FOOD_DETAILS_CLEAR = 'FOOD_DETAILS_CLEAR';
