export const INTAKE_LIST_REQUEST = 'INTAKE_LIST_REQUEST';
export const INTAKE_LIST_SUCCESS = 'INTAKE_LIST_SUCCESS';
export const INTAKE_LIST_FAIL = 'INTAKE_LIST_FAIL';

export const INTAKE_ADD_REQUEST = 'INTAKE_ADD_REQUEST';
export const INTAKE_ADD_SUCCESS = 'INTAKE_ADD_SUCCESS';
export const INTAKE_ADD_FAIL = 'INTAKE_ADD_FAIL';
export const INTAKE_ADD_CLEAR = 'INTAKE_ADD_CLEAR';

export const INTAKE_DELETE_REQUEST = 'INTAKE_DELETE_REQUEST';
export const INTAKE_DELETE_SUCCESS = 'INTAKE_DELETE_SUCCESS';
export const INTAKE_DELETE_FAIL = 'INTAKE_DELETE_FAIL';
