export const REQUIREMENTS_LIST_REQUEST = 'REQUIREMENTS_LIST_REQUEST';
export const REQUIREMENTS_LIST_SUCCESS = 'REQUIREMENTS_LIST_SUCCESS';
export const REQUIREMENTS_LIST_FAIL = 'REQUIREMENTS_LIST_FAIL';

export const REQUIREMENTS_UPDATE_REQUEST = 'REQUIREMENTS_UPDATE_REQUEST';
export const REQUIREMENTS_UPDATE_SUCCESS = 'REQUIREMENTS_UPDATE_SUCCESS';
export const REQUIREMENTS_UPDATE_FAIL = 'REQUIREMENTS_UPDATE_FAIL';

export const REQUIREMENT_UPDATE_RESET = 'REQUIREMENTS_UPDATE_RESET';
