export const WEIGHT_LIST_REQUEST = 'WEIGHT_LIST_REQUEST';
export const WEIGHT_LIST_SUCCESS = 'WEIGHT_LIST_SUCCESS';
export const WEIGHT_LIST_FAIL = 'WEIGHT_LIST_FAIL';

export const DAILY_SUM_REQUEST = 'DAILY_SUM_REQUEST';
export const DAILY_SUM_SUCCESS = 'DAILY_SUM_SUCCESS';
export const DAILY_SUM_FAIL = 'DAILY_SUM_FAIL';

export const MEAL_AVG_REQUEST = 'MEAL_AVG_REQUEST';
export const MEAL_AVG_SUCCESS = 'MEAL_AVG_SUCCESS';
export const MEAL_AVG_FAIL = 'MEAL_AVG_FAIL';
